version: '3.6'

services:
  web:
    build: .
    command: gunicorn kaliblog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-db
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  postgres_data: