# Generated by Django 2.2 on 2020-05-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_duration',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='words_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
