# Generated by Django 2.2 on 2020-05-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200528_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='approved',
            new_name='approve',
        ),
        migrations.AlterField(
            model_name='post',
            name='read_duration',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
